### ISSUE TITLE
Shortcuts in start menu should be created for all users

### ISSUE THREAD

**Issue by czthuyvu** [rabbitmq/rabbitmq-packaging#10]
**Environment:**
Windows 10

**Pre-condition:**
1. Erlang was installed.
2. 2 Users are available: a non-admin user A, an admin user B.

**Steps to reproduce:**
1. Log into Windows as User A
2. Install RabbitMQ
-> A popup window will be prompt to ask for an admin user.
![2022-01-05 17_00_20-Window](https://user-images.githubusercontent.com/78349053/148248864-264d4785-f270-4a7e-9e39-96394644b8c9.png)
3. Enter username and password of User B to continue.
4. Complete the installation

**Actual results:**
- RabbitMQ was installed for all users
- All shortcuts in start menu are only available for user B.

**Expected results:**
- All shortcuts in start menu are available for all users.

![2022-01-05 17_14_50-Window](https://user-images.githubusercontent.com/78349053/148251055-bea1363a-5b5b-4f3f-a8d1-05772e89ffe4.png)

**Comment by lukebakken** [comment]
> RabbitMQ was installed for all users

RabbitMQ is installed system-wide, but only user B should have access to the shortcuts since they depend on admin permissions.

Also note that RabbitMQ's data is stored in User B's `%APPDATA%\RabbitMQ` directory. Someday this may be changed to make a bit more sense.

We appreciate the report but this is not going to be changed at this time.
