### ISSUE TITLE
deb... does not have a Release file

### ISSUE THREAD

**Issue by jaguart** [rabbitmq/rabbitmq-packaging#17]
This warning is emitted daily in logs, following recent installation on Debian bullseye on 10 July 2022.

```
E: The repository 'https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bullseye Release' does not have a Release file.
```

This is a vanilla install, the ``sources.list.d/rabbitmq.list`` file contains: 
```
## Provides modern Erlang/OTP releases
##
## The Ubuntu PPA is not aware of Debian distribution names.
## "bionic" as distribution name should work for any reasonably recent Ubuntu or Debian release.
deb [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.E495BB49CC4BBE5B.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu bionic main
deb-src [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.E495BB49CC4BBE5B.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu bionic main

## Provides RabbitMQ - BULLSEYE
##
deb [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.9F4587F226208342.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bullseye main
deb-src [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.9F4587F226208342.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bullseye main

```

**Comment by michaelklishin** [comment]
We do not have control over Cloudsmith and this hasn't been reported elsewhere. I will forward it to their support folks. Thanks.
________________________________
From: Jeff ***@***.***>
Sent: Wednesday, July 20, 2022 3:00:54 PM
To: rabbitmq/rabbitmq-packaging ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rabbitmq/rabbitmq-packaging] deb... does not have a Release file (Issue #17)


⚠ External Email

This warning is emitted daily in logs, following recent installation on Debian bullseye on 10 July 2022.

E: The repository 'https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bullseye Release' does not have a Release file.


This is a vanilla install, the sources.list.d/rabbitmq.list file contains:

## Provides modern Erlang/OTP releases
##
## The Ubuntu PPA is not aware of Debian distribution names.
## "bionic" as distribution name should work for any reasonably recent Ubuntu or Debian release.
deb [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.E495BB49CC4BBE5B.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu bionic main
deb-src [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.E495BB49CC4BBE5B.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu bionic main

## Provides RabbitMQ - BULLSEYE
##
deb [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.9F4587F226208342.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bullseye main
deb-src [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.9F4587F226208342.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bullseye main



—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frabbitmq%2Frabbitmq-packaging%2Fissues%2F17&data=05%7C01%7Cklishinm%40vmware.com%7C7447199eea88437aff9208da6a3f1e65%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637939116575608964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TslBSy7sHv18xUCyb4LhizRe7WGlkt3%2FtjVMVTlM0xw%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAAIQQDBJTPBFINCQGWU6TVU7L6NANCNFSM54DGHVUQ&data=05%7C01%7Cklishinm%40vmware.com%7C7447199eea88437aff9208da6a3f1e65%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637939116575608964%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HFpqJIYbih9TT0qoVMBEdp0RDjaUz8Ehmgda9MXs%2FeA%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________

⚠ External Email: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender.

**Comment by michaelklishin** [comment]
> deb/ubuntu bullseye main

is the part you should be looking at. Either use Ubuntu Bionic or Debian Bullseye, "Ubuntu Bullseye" is not a thing.
